spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@stockon.rgg7ygu.mongodb.net/?retryWrites=true&w=majority
      database: subwaydb

subway:
  openApi:
    realtimeArrival:
      uri: http://swopenapi.seoul.go.kr/
    apiKey: 4974615957726c6135336e43515952
